import type { ClientGameState, GameState } from './types.js';
import { resolvedEnemyAttack } from './engine.js';

/** Produces the per-player view of state: every hand except the viewer's own is collapsed to a count. */
export function redactStateFor(state: GameState, viewerPlayerId: string): ClientGameState {
  return {
    phase: state.phase,
    ruleset: state.ruleset,
    players: state.players.map((p) => ({
      id: p.id,
      name: p.name,
      connected: p.connected,
      handCount: p.hand.length,
      kinfolkSlot: p.kinfolkSlot,
      ...(p.id === viewerPlayerId ? { hand: p.hand } : {}),
    })),
    currentPlayerIndex: state.currentPlayerIndex,
    turnPhase: state.turnPhase,
    pendingDamage: state.pendingDamage,
    currentEnemy: state.currentEnemy,
    liveEnemyAttack: state.currentEnemy ? resolvedEnemyAttack(state) : null,
    castleDeckCount: state.castleDeck.length,
    tavernDeckCount: state.tavernDeck.length,
    discardPile: state.discardPile,
    maxHandSize: state.maxHandSize,
    log: state.log,
    lossReason: state.lossReason,
    soloJestersUsed: state.soloJestersUsed,
    victoryMedal: state.victoryMedal,
    jesterClaim: state.jesterClaim,
    standingJesters: state.standingJesters,
    endlessLoop: state.endlessLoop,
    comboAssist: state.comboAssist,
    scarletWhistleSoloChoice: state.scarletWhistleSoloChoice,
    relics: state.relics,
    corruptedRelics: state.corruptedRelics,
    kinfolkBankedThisTurn: state.kinfolkBankedThisTurn,
    azureEmblemWindow: state.azureEmblemWindow,
    mageReveal: state.mageReveal,
    reaverRevealCountChoice: state.reaverRevealCountChoice,
    reaverReveal: state.reaverReveal,
    discardTopBuffsAttack: state.discardTopBuffsAttack,
    missionZone: state.missionZone,
    rollingZoneBonus: state.rollingZoneBonus,
    rollingZoneCards: state.rollingZoneCards,
    zoneVengeanceOnKill: state.zoneVengeanceOnKill,
    zoneVengeanceChoice: state.zoneVengeanceChoice,
    zoneReliefChoice: state.zoneReliefChoice,
    pilgrimMechanic: state.pilgrimMechanic,
    pilgrimZone: state.pilgrimZone,
    pilgrimDeckCount: state.pilgrimDeck.length,
    ascendingZone: state.ascendingZone,
    zoneOpenForPlacement: state.zoneOpenForPlacement,
    zoneCommittedPlay: state.zoneCommittedPlay,
    zoneClosed: state.zoneClosed,
    zonePurge: state.zonePurge,
    chanterCountChoice: state.chanterCountChoice,
    chanterWindow: state.chanterWindow,
    druidWindow: state.druidWindow,
    capturedPilesActive: state.capturedPilesActive,
    capturedPiles: state.capturedPiles.map((p) => ({ faceUp: p.faceUp, faceDownCount: p.faceDown.length })),
    zoneImmuneSuits: state.zoneImmuneSuits,
    banishPile: state.banishPile,
    beastDeckMechanic: state.beastDeckMechanic,
    beastDeckCount: state.beastDeck.length,
    beastDeckDiscard: state.beastDeckDiscard,
    restoredCardMechanic: state.restoredCardMechanic,
    you: { playerId: viewerPlayerId },
  };
}
